# EC2 Key Pair - generated by Terraform; private key written locally and stored in Secrets Manager

resource "tls_private_key" "ghost" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "ghost" {
  key_name   = "${var.project_name}-${var.environment}-key"
  public_key = tls_private_key.ghost.public_key_openssh

  tags = {
    Name = "${var.project_name}-ec2-key"
  }
}

# Save private key locally (infra/ghost-key.pem, gitignored) so you can SSH after apply
resource "local_file" "ghost_private_key" {
  filename             = "${path.module}/ghost-key.pem"
  content              = tls_private_key.ghost.private_key_pem
  file_permission      = "0400"
  directory_permission = "0700"
}

# Save same private key in Secrets Manager (same key as ghost-key.pem)
resource "aws_secretsmanager_secret" "ec2_private_key" {
  name        = "${var.project_name}/${var.environment}/ec2-ssh-private-key"
  description = "EC2 SSH private key (same as infra/ghost-key.pem). Stored in Secrets Manager and locally."

  tags = {
    Name = "${var.project_name}-ec2-private-key"
  }
}

resource "aws_secretsmanager_secret_version" "ec2_private_key" {
  secret_id     = aws_secretsmanager_secret.ec2_private_key.id
  secret_string = tls_private_key.ghost.private_key_pem
}
